#BACKLIGHT_ENABLE = no
#RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
#MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
#VIAL_ENABLE = yes
#VIAL_INSCURE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom

CONSOLE_ENABLE = no         # Console for debug
LTO_ENABLE = yes
QMK_SETTINGS = no
EXTRAFLAGS+=-flto

#OPT_DEFS += -DBOOTLOADER_SIZE=4096
#OPT_DEFS += -DBOOTLOADER_SIZE=1024

SRC += v99slim.c
